### ISSUE TITLE
Javascript Docu

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/conventions#31] opened 2015-04-22 07:30 UTC
use jsDocs (http://usejsdoc.org/)

**Comment by ain** [comment] 2015-04-22 09:31
I'd go for JSDoc only if we're dealing with API documentation. In other cases I'd favour readable code over comments, reason being:

<blockquote class="twitter-tweet" lang="en"><p>Code comments <a href="http://t.co/2KDRdfFE9u">pic.twitter.com/2KDRdfFE9u</a></p>&mdash; Michael Koziarski (@nzkoz) <a href="https://twitter.com/nzkoz/status/538892801941848064">November 30, 2014</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by ain** [comment] 2015-04-22 11:26
Dupe of #16.

**Closed by ain** 2015-04-22 11:26 UTC
Labels: duplicate, enhancement, question
